
[master]
name            = "[WIP] Right-click Axe"
tags            = ["WIP", "Balance", "Must be run on server"]
autodescription = true
description     = "README.md"
preview         = "/dev/null"

[beta]
name            = "[WIP] Right-click Axe - Beta"
tags            = ["WIP", "Beta", "Balance", "Must be run on server"]
autodescription = false
description     = "description.beta.txt"
preview         = "/dev/null"
